// navbar controls and navbar hamburger sidebar controls

// searchbox open close controls
let navbar = document.querySelector(".navbar");
let searchBox = document.querySelector(".search-box .fa-magnifying-glass");
let searchBoxCancel = document.querySelector(".search-box .fa-xmark");

searchBox.addEventListener("click", ()=>{
    navbar.classList.toggle("showInput");
        if(navbar.classList.contains("showInput")) {
        searchBox.classList.replace("fa-magnifying-glass" ,"fa-xmark");
        }else {
        searchBox.classList.replace("fa-xmark" ,"fa-magnifying-glass");
        }
    }
);
 
// sidebar open close controls
let navLinks = document.querySelector(".nav-links");
let menuOpenBtn = document.querySelector(".navbar .fa-bars");
let menuCloseBtn = document.querySelector(".nav-links .fa-xmark");

menuOpenBtn.onclick = function() {
    navLinks.style.left = "0";
}
menuCloseBtn.onclick = function() {
    navLinks.style.left = "-100%";
}
 
// sidebar submenu open close controls
let reasonsArrow = document.querySelector(".reasons-arrow");

reasonsArrow.onclick = function() {
    navLinks.classList.toggle("show1");
}
 
let aboutUsArrow = document.querySelector(".aboutus-arrow");

aboutUsArrow.onclick = function() {
    navLinks.classList.toggle("show2");
}

// scroll to top button

// Get the button:
let Btn = document.getElementById("scrollToTopBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    Btn.style.display = "block";
  } else {
    Btn.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function scrollToTop() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}

// footer-disclaimer modal

// Get the modal
var modal = document.getElementById("myModal");

// Get the span that opens modal
var trigger = document.getElementById("modalTrigger");

// Get button that closes modal
var btn = document.getElementsByClassName("close")[0];

// When the user clicks on the button, open the modal
trigger.onclick = function disclaimerOpen() {
  modal.style.display = "block";
}

// button to close the modal onclick
btn.onclick = function disclaimerClose() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

// crystal ball reason generator

var generatorTrigger = document.getElementById("genTrigger")
var imgElement = document.getElementById("generator-img")
var pElement = document.getElementById("generator-p")
var optionElement = document.getElementById("generator-options")
var resultElement = document.getElementById("result-p")


document.addEventListener('DOMContentLoaded', function startQuestion() {

  generatorTrigger.addEventListener("click", function () {
      
      // elements to change upon click
      imgElement.style.opacity = "100%";
      generatorTrigger.style.display = "none";
      generatorTrigger.innerText = "Troubled One, what type of reason do you seek?";
      pElement.style.display = "block";
      optionElement.style.display = "block";
  });

  optionElement.addEventListener("click", function () {
      
    // elements to change upon click
    imgElement.style.display = "none";
    pElement.style.display = "none";
    optionElement.style.display = "none";
    /*resultElement.style.cssText = `
    display: flex;
    font-size: 3rem;
    padding: none;
    margin: none;
    top: 0;
    left:0;
    `*/
    resultElement.style.display = "block";   
  });
  
});

// functions to call up the different random img generator for each option

function generateCoding() {  
  //array to store the images  
  var imageArrayCoding = new Array();  
    
  //images in array  
  imageArrayCoding[0] = "pictures/card-codingreason1.png";  
  imageArrayCoding[1] = "pictures/card-codingreason2.png";  
  imageArrayCoding[2] = "pictures/card-codingreason3.png";  
  imageArrayCoding[3] = "pictures/card-codingreason4.png";   
    
  //generate a number and provide to the image to generate randomly  
  var number = Math.floor(Math.random()*imageArrayCoding.length);  
    
  //return the images generated by random number  
  return document.getElementById("generator-result").innerHTML = '<img src="'+imageArrayCoding[number]+'" width="80%" height="80%"/>';  
}  

function generatePerservere() {  
  //array to store the images  
  var imageArrayPerservere = new Array();  
    
  //images in array  
  imageArrayPerservere[0] = "pictures/card-perserverereason1.png";  
  imageArrayPerservere[1] = "pictures/card-perserverereason2.png";  
  imageArrayPerservere[2] = "pictures/card-perserverereason3.png";  
  imageArrayPerservere[3] = "pictures/card-perserverereason4.png";  
  imageArrayPerservere[4] = "pictures/card-perserverereason5.png";  
  imageArrayPerservere[5] = "pictures/card-perserverereason6.png";
  imageArrayPerservere[6] = "pictures/card-perserverereason7.png";
  imageArrayPerservere[7] = "pictures/card-perserverereason8.png";
    
  //generate a number and provide to the image to generate randomly  
  var number = Math.floor(Math.random()*imageArrayPerservere.length);  
    
  //return the images generated by a random number  
  return document.getElementById("generator-result").innerHTML = '<img src="'+imageArrayPerservere[number]+'" width="80%" height="80%" />';  
}  

function generateSelfLove() {  
  //array to store the images  
  var imageArraySelfLove = new Array();  
    
  //images in array  
  imageArraySelfLove[0] = "pictures/card-selflovereason1.png";  
  imageArraySelfLove[1] = "pictures/card-selflovereason2.png";  
  imageArraySelfLove[2] = "pictures/card-selflovereason3.png";  
  imageArraySelfLove[3] = "pictures/card-selflovereason4.png";  
  imageArraySelfLove[4] = "pictures/card-selflovereason5.png";  
    
  //generate a number and provide to the image to generate randomly  
  var number = Math.floor(Math.random()*imageArraySelfLove.length);  
    
  //return the images generated by a random number  
  return document.getElementById("generator-result").innerHTML = '<img src="'+imageArraySelfLove[number]+'" width="80%" height="80%"/>';  
}

function generateProcrastinate() {  
  //array to store the images  
  var imageArrayProcrastinate = new Array();  
    
  //images in array  
  imageArrayProcrastinate[0] = "pictures/card-procrastinatereason1.png";  
  imageArrayProcrastinate[1] = "pictures/card-procrastinatereason2.png";  
  imageArrayProcrastinate[2] = "pictures/card-procrastinatereason3.png";  
  imageArrayProcrastinate[3] = "pictures/card-procrastinatereason4.png";  
  imageArrayProcrastinate[4] = "pictures/card-procrastinatereason5.png";
  imageArrayProcrastinate[5] = "pictures/card-procrastinatereason6.png";
  imageArrayProcrastinate[6] = "pictures/card-procrastinatereason7.png";
  imageArrayProcrastinate[7] = "pictures/card-procrastinatereason8.png";
    
  //generate a number and provide to the image to generate randomly  
  var number = Math.floor(Math.random()*imageArrayProcrastinate.length);  
    
  //return the images generated by a random number  
  return document.getElementById("generator-result").innerHTML = '<img src="'+imageArrayProcrastinate[number]+'" width="80%" height="80%"/>';  
}  

function generateLucky() {  
  //array to store the images  
  var imageArrayLucky = new Array();  
    
  //images in array  
  imageArrayLucky[0] = "pictures/card-lucky.png";  
  imageArrayLucky[1] = "pictures/card-unlucky.png";  
    
  //generate a number and provide to the image to generate randomly  
  var number = Math.floor(Math.random()*imageArrayLucky.length);  
    
  //return the images generated by a random number  
  return document.getElementById("generator-result").innerHTML = '<img src="'+imageArrayLucky[number]+'" width="80%" height="80%" />';  
}  




